//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stock_Market.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        private int id1;
        private int id2;
        private int numberShares;
        private double currentPrice;
        private string td;
        private string v;

        public Transaction(int id1, int id2, int numberShares, double currentPrice, string td, string v)
        {
            this.id1 = id1;
            this.id2 = id2;
            this.numberShares = numberShares;
            this.currentPrice = currentPrice;
            this.td = td;
            this.v = v;
        }

        public int TransactionId { get; set; }
        public int UserID { get; set; }
        public int StockID { get; set; }
        public int StockAmount { get; set; }
        public decimal Price { get; set; }
        public string Trade { get; set; }
    
        public virtual Stock Stock { get; set; }
        public virtual User User { get; set; }
    }
}
